### ISSUE TITLE
This line is not idempotent :-). Why you all facing same issues ? SURPRISED ))))

### ISSUE THREAD

**Issue by onbayev** [AlexandrSher/CHEF#1]
https://github.com/AlexandrSher/CHEF/blob/c1d3b4586fd05b52cb8f6becb4a7c31112a6c54f/cookbooks/jboss/recipes/default.rb#L31

**Comment by AlexandrSher** [comment]
Yep sure!))) But if we had had more time to learn chef we wouldn't have made this mistake 100%)))))
